// frontend/vue/src/pages/construct-building.vue
<template>
  <div class="flex flex-col items-center justify-center mt-5 space-y-10">
    <span class="text-5xl font-bold">Building Builder</span>
    <MessageBlock v-if="message" :message="message" />
    <Card>
      <template #content>
        <div class="flex flex-col gap-4">
          <p class="label">
            Where:
          </p>
          <div class="flex gap-4 w-full">
            <div class="flex flex-col flex-1">
              <label for="x" class="label">X:</label>
              <InputNumber
                show-buttons
                v-model="x"
                input-id="x"
              />
            </div>
            <div class="flex flex-col flex-1">
              <label for="y" class="label">Y:</label>
              <InputNumber
                show-buttons
                v-model="y"
                input-id="y"
              />
            </div>
          </div>
          <div class="flex gap-4 w-full">
            <div class="flex-1">
              <label for="type_id" class="label">Build:</label>
              <Dropdown
                :options="buildingTypes"
                v-model="buildingType"
                option-label="title"
                class="w-full"
              />
            </div>
            <div class="flex-1 self-center text-xl">
              {{ buildingType.description }}
            </div>
          </div>
          <div class="flex flex-col">
            <label for="square" class="label">Square:</label>
            <InputNumber
              show-buttons
              v-model="square"
              input-id="square"
            />
          </div>
          <div class="flex space-x-3">
            <div class="flex flex-col">
              <div class="flex gap-4">
                <p class="label">
                  Cost:
                </p>
                <p class="text-xl underline">
                  {{ buildingType.cost * square }}$
                </p>
              </div>
              <div class="flex gap-4">
                <p class="label">
                  Time:
                </p>
                <p class="text-xl underline">
                  {{ formatDuration(buildingType.buildTime * square / 1000000000) }}
                </p>
              </div>
            </div>
          </div>

          <Button
            label="Construct"
            class="bg-indigo-500"
            @click="construct"
          />
        </div>
      </template>
    </Card>
  </div>
</template>

<script setup lang="ts">
import Button from 'primevue/button'
import Card from 'primevue/card'
import Dropdown from 'primevue/dropdown'
import InputNumber from 'primevue/inputnumber'
import { ref } from 'vue'
import { useRoute } from 'vue-router'
import MessageBlock from '@/components/Common/MessageBlock.vue'
import { useBuildings } from '@/composables/useBuildings'
import { useGetData } from '@/composables/useGetData'
import type { Message } from '@/types'
import type { BuildingType } from '@/types/Buildings/index.interface'
import { formatDuration } from '@/utils/formatDuration'

const { query } = useRoute()

const x = ref<number>(Number(query.x))
const y = ref<number>(Number(query.y))
const buildingType = ref<BuildingType>({} as BuildingType)
const square = ref<number>(10)
const message = ref<Message | null>(null)

const { data: buildingTypes, onFetchResponse } = useGetData<BuildingType[]>('/building/types')
onFetchResponse(() => {
  buildingType.value = buildingTypes.value[0]
})

const { constructBuilding } = useBuildings()

const construct = () => {
  message.value = null

  const payload = {
    x: x.value,
    y: y.value,
    typeId: buildingType.value.id,
    square: square.value
  }

  const { dataMessage, onFetchFinally } = constructBuilding(payload)
  onFetchFinally(() => {
    message.value = dataMessage.value
  })
}

</script>

<style scoped>
.label {
  @apply block text-xl font-bold mb-2;
}
</style>

// frontend/react/src/pages/ConstructBuilding.tsx
import React, { useState } from 'react'
import { useParams } from 'react-router-dom'
import { Error } from '../components/Error'
import { Success } from '../components/Success'
import { constructBuilding } from '../hooks/constructBuilding'
import { useGetData } from '../hooks/getData'
import { formatDuration } from '../include/formatDuration'
import { IBuildingTypes } from '../models'

export const ConstructBuilding = () => {
  const { xParam, yParam } = useParams()
  const [x, setX] = useState(Number(xParam))
  const [y, setY] = useState(Number(yParam))
  const [typeID, setTypeID] = useState<number>(1)
  const [square, setSquare] = useState<number>(10)
  const [error, setError] = useState('')
  const [message, setMessage] = useState('')
  const buildingTypes = useGetData<IBuildingTypes>('/building/types')
  const buildingTypeSelected = buildingTypes?.find(element => element.id === typeID)

  const submitHandler = (event: React.FormEvent) => {
    setError('')
    setMessage('')
    event.preventDefault()
    constructBuilding(x, y, typeID, square, setMessage, setError)
  }

  return (
    <>
      <div className="flex flex-col items-center justify-center mt-5 space-y-10">
        <span className="text-5xl font-bold">Building Builder</span>
        {message && <Success message={message}/> }
        {error && <Error error={error}/> }
        <form className="flex justify-center" onSubmit={submitHandler}>
          <div className="mb-4 space-y-5">
            <label htmlFor="x" className="block text-xl font-bold">Where:</label>
            <div className="flex space-x-3">
              <div className="flex flex-col">
                <label htmlFor="x" className="block text-xl font-bold">X:</label>
                <input type="number" id="x" name="x" value={x}
                  className="mt-1 border-indigo-800 border-2 rounded-md px-2"
                  onChange={(e) =>
                    setX(Number(e.target.value))}
                />
              </div>
              <div className="flex flex-col">
                <label htmlFor="y" className="block text-xl font-bold">Y:</label>
                <input type="number" id="y" name="y" value={y}
                  className="mt-1 border-indigo-800 border-2 rounded-md px-2"
                  onChange={(e) =>
                    setY(Number(e.target.value))}
                />
              </div>
            </div>
            <label htmlFor="type_id" className="block text-xl font-bold">Build:</label>
            <select id="type_id" name="type_id"
              className="mt-1 border-indigo-800 border-2 rounded-md pl-3 pr-10 text-base"
              onChange={(e) => setTypeID(Number(e.target.value))}>
              {buildingTypes?.map((buildingType, Index) => {
                return (
                  <option key={Index} value={buildingType.id}>{buildingType.title}</option>
                )
              })}
            </select>
            <div className="mt-2">{buildingTypeSelected?.description}</div>
            <div className="flex space-x-3">
              <div className="flex flex-col">
                <label htmlFor="x" className="block text-xl font-bold">Square:</label>
                <input type="number" id="square" name="square" placeholder="10"
                  className="mt-5 border-indigo-800 border-2 rounded-md pl-3"
                  onChange={(e) => setSquare(Number(e.target.value))}
                />
              </div>
            </div>
            <div className="flex space-x-3">
              <div className="flex flex-col">
                <label htmlFor="x" className="block text-xl font-bold">Cost:</label>
                {buildingTypeSelected && buildingTypeSelected.cost * square}
                <label htmlFor="x" className="block text-xl font-bold">Time:</label>
                {buildingTypeSelected && formatDuration(buildingTypeSelected.buildTime * square / 1000000000)}
              </div>
            </div>

            <button type="submit"
              className="bg-indigo-500 text-white py-2 px-4 rounded-md hover:bg-indigo-600">Construct
            </button>
          </div>
        </form>
      </div>

    </>
  )
}
