// frontend/vue/src/components/Logistics/Logistics.vue
<template>
  <h2 class="font-bold text-2xl">
    {{ t(`logistics.title`) }}
  </h2>
  <DataTable
    v-if="!isFetching"
    :value="logistics"
    size="small"
    striped-rows
  >
    <Column
      field="resourceName"
      :header="t(`logistics.columns.resource`)"
    />
    <Column
      :header="t(`logistics.columns.from`)"
    >
      <template #body="{data}: {data: Logistic}">
        {{ data.fromX }}x{{ data.fromY }}
      </template>
    </Column>
    <Column
      :header="t(`logistics.columns.to`)"
    >
      <template #body="{data}: {data: Logistic}">
        {{ data.toX }}x{{ data.toY }}
      </template>
    </Column>
    <Column
      field="amount"
      :header="t(`logistics.columns.amount`)"
    />
    <Column
      :header="t(`logistics.columns.finish`)"
    >
      <template #body="{data}: {data: Logistic}">
        {{ getTimeDiff(data.workEnd) > 0 ? formatDuration(getTimeDiff(data.workEnd)) : '' }}
      </template>
    </Column>
  </DataTable>
  <Loading v-else />
</template>

<script setup lang="ts">
import Column from 'primevue/column'
import DataTable from 'primevue/datatable'
import { useI18n } from 'vue-i18n'
import Loading from '@/components/Common/Loading.vue'
import { useGetData } from '@/composables/useGetData'
import { Logistic } from '@/types'
import { formatDuration } from '@/utils/formatDuration'
import { getTimeDiff } from '@/utils/getTimeDiff'

const { data: logistics, isFetching } = useGetData<Logistic[]>('/resource/my_logistics')
const { t } = useI18n()
</script>

// frontend/react/src/pages/Logistics.tsx
import React from 'react'
import { useGetData } from '../hooks/getData'
import { formatDuration } from '../include/formatDuration'
import { ILogistics } from '../models'

const LogisticsPage = () => {
  const myLogistics = useGetData<ILogistics>('/resource/my_logistics')

  return (
    <div className="p-4 shadow-xl">
      <h2 className="font-bold text-2xl">Logistics</h2>
      <div className="grid grid-cols-5 font-bold">
        <h3 className="col-span-1">Resource</h3>
        <h3 className="col-span-1">From </h3>
        <h3 className="col-span-1">To </h3>
        <h3 className="col-span-1">Amount</h3>
        <h3 className="col-span-1">Finish</h3>
      </div>
      <div className="">
        {myLogistics?.map((logistic, Index) => {
          let diffS: number | null
          const now = new Date()
          logistic.workEnd = new Date(logistic.workEnd)
          diffS = Math.floor((logistic.workEnd.getTime() - now.getTime()) / 1000)
          if (diffS < 0) diffS = null
          return (
            <div className="grid grid-cols-5 " key={Index}>
              <p className="col-span-1">{logistic.resourceName}</p>
              <p className="col-span-1">{logistic.fromX}x{logistic.fromY}</p>
              <p className="col-span-1">{logistic.toX}x{logistic.toY}</p>
              <p className="col-span-1">{logistic.amount}</p>
              <p className="col-span-1">{diffS && formatDuration(diffS)}</p>
            </div>
          )
        })
        }
      </div>
    </div>
  )
}

export default LogisticsPage
