// frontend/vue/src/pages/search-building.vue
<template>
  <Layout>
    <template #options>
      <Dropdown
        :options="buildingTypes"
        option-label="title"
        v-model="buildingType"
        @change="event => setParams({key: 'buildingTypeId', value: event.value.id})"
      >
        <template #option="{option}">
          {{ getBuildingTypeName(option) }}
        </template>
        <template #value="{value}">
          {{ getBuildingTypeName(value) }}
        </template>
      </Dropdown>
      <div class="slider">
        <span>X: {{ x }}</span>
        <div class="flex items-center gap-4">
          <span class="text-sm">{{ coords?.mapMinX }}</span>
          <Slider
            v-model="x"
            :max="coords?.mapMaxX"
            :min="coords?.mapMinX"
            @change="value => x = value"
            class="w-[150px]"
            @slideend="event => setParams({key: 'x', value: event.value})"
          />
          <span class="text-sm">{{ coords?.mapMaxX }}</span>
        </div>
      </div>
      <div class="slider">
        <span>Y: {{ y }}</span>
        <div class="flex items-center gap-4">
          <span class="text-sm">{{ coords?.mapMinY }}</span>
          <Slider
            v-model="y"
            :max="coords?.mapMaxY"
            :min="coords?.mapMinY"
            @change="value => y = value"
            class="w-[150px]"
            @slideend="event => setParams({key: 'y', value: event.value})"
          />
          <span class="text-sm">{{ coords?.mapMaxY }}</span>
        </div>
      </div>
      <AutoComplete
        v-model="userSearch"
        :suggestions="users"
        :delay="1000"
        @complete="searchUsers"
        @item-select="event => setParams({key: 'nickName', value: event.value})"
        dropdown
      />

      <Button :label="t('common.reset')" @click="clearParams" />
    </template>
    <BuildingSearch :search-params="params" />
  </Layout>
</template>

<script setup lang="ts">
import AutoComplete from 'primevue/autocomplete'
import Button from 'primevue/button'
import Dropdown from 'primevue/dropdown'
import Slider from 'primevue/slider'
import { ref } from 'vue'
import { useI18n } from 'vue-i18n'
import BuildingSearch from '@/components/Buildings/SearchBuilding/BuildingSearch.vue'
import Layout from '@/components/Common/Layout.vue'
import { useGetData } from '@/composables/useGetData'
import type { Coords } from '@/types'
import type { BuildingType, SearchBuildingParams } from '@/types/Buildings/index.interface'

const buildingType = ref<BuildingType>({ id: 0, title: 'All' })
const buildingTypes = ref<BuildingType[]>([{ id: 0, title: 'All' }])
const x = ref<number>()
const y = ref<number>()
const userSearch = ref<string>('')
const users = ref<string[]>([])

const { t } = useI18n()

const { data, onFetchResponse } = useGetData<BuildingType[]>('/building/types')
onFetchResponse(() => {
  buildingTypes.value = [...buildingTypes.value, ...data.value]
})

const { data: coords } = useGetData<Record<Coords, number>>('/settings')

const getBuildingTypeName = (type: BuildingType) => {
  return t(`buildings.types.${type?.title.toLocaleLowerCase()}`)
}

const searchUsers = () => {
  const { data, onFetchResponse } = useGetData<string[]>(`/data/users_by_prefix?prefix=${userSearch.value}`)
  onFetchResponse(() => {
    users.value = data.value
  })
}

const params = ref<SearchBuildingParams>({
  limit: -1
})

const setParams = ({ key, value }: {key: string; value: number}) => {
  params.value[key] = value

  if (!buildingType.value.id) {
    delete params.value.buildingTypeId
  }
}

const clearParams = () => {
  params.value = {
    limit: -1
  }
  userSearch.value = ''
}

</script>

<style scoped>
.slider {
  @apply w-full flex items-center justify-between;
}
</style>

// frontend/react/src/pages/SearchBuilding.tsx
import { AutoComplete, AutoCompleteCompleteEvent } from 'primereact/autocomplete'
import { Button } from 'primereact/button'
import { Column } from 'primereact/column'
import { DataTable } from 'primereact/datatable'
import { Dropdown, DropdownChangeEvent } from 'primereact/dropdown'
import { Slider, SliderChangeEvent } from 'primereact/slider'
import React, { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { useAxios } from '../hooks/useAxios'
import { IBuildings, IBuildingTypes } from '../models'

interface Params {
  limit: '-1';
  nick_name?: string;
  x?: string;
  y?: string;
  building_type_id?: string;
}

type Coords = 'mapMaxX' | 'mapMaxY' | 'mapMinX' | 'mapMinY'

const SearchBuilding = () => {
  const [searchUrl, setSearchUrl] = useState<string>('/building/get?limit=-1&')
  const [params, setParams] = useState<Params>({} as Params)
  const [buildingType, setBuildingType] = useState<number>()
  const [x, setX] = useState<number>(0)
  const [y, setY] = useState<number>(0)
  const [search, setSearch] = useState('')
  const [users, setUsers] = useState<Record<string, number>[] | undefined>([])
  const { t } = useTranslation()

  const { response: buildings } = useAxios<IBuildings[]>(searchUrl)
  const { response: coords } = useAxios<Record<Coords, number>>('/settings', { initialData: {} })
  const { mapMaxX, mapMaxY, mapMinX, mapMinY }: Record<Coords, number> = coords
  const { response: data } = useAxios<IBuildingTypes[]>('/building/types')
  const buildingTypes: IBuildingTypes[] = [{ id: 0, title: 'All' } as IBuildingTypes, ...data]

  useEffect(() => {
    const p = { ...params } as Record<string, string>
    setSearchUrl(`/building/get?${new URLSearchParams(p).toString()}`)
  }, [params])

  const onChangeBuildingType = (event: DropdownChangeEvent) => {
    setBuildingType(event.target.value)
    setParams(current => {
      let copy = { ...current }
      if (!event.target.value) {
        delete copy['building_type_id']
      }
      else {
        copy = { ...copy, building_type_id: event.target.value.toString() }
      }
      return copy
    })
  }

  const onChangeX = (event: SliderChangeEvent) => {
    setX(event.value as number)
    setParams({ ...params, x: event.value.toString() })
  }

  const onChangeY = (event: SliderChangeEvent) => {
    setY(event.value as number)
    setParams({ ...params, y: event.value.toString() })
  }

  const buildingTypeTemplate = (option: IBuildingTypes) => {
    return (
      <span>{t(`buildings.types.${option?.title.toLocaleLowerCase()}`)}</span>
    )
  }

  const { axiosFetch } = useAxios<Record<string, number>[]>()

  const searchUsers = async (event: AutoCompleteCompleteEvent) => {
    setSearch(event.query)
    const response = await axiosFetch(`/data/users_by_prefix?prefix=${event.query}`)
    setUsers(response)
  }

  const clear = () => {
    setBuildingType(0)
    setParams({} as Params)
    setSearch('')
  }

  return (
    <div className="px-4 py-8">
      <div className="mb-4 flex gap-12 items-center">
        <span className="p-float-label">
          <Dropdown
            inputId="b-type"
            value={buildingType}
            options={buildingTypes}
            optionLabel="title"
            optionValue="id"
            onChange={onChangeBuildingType}
            className="w-[200px]"
            itemTemplate={buildingTypeTemplate}
            valueTemplate={buildingTypeTemplate}
          />
          <label htmlFor="b-type">{t('buildings.type')}</label>
        </span>
        <div className="slider">
          <span>X: {x}</span>
          <div className="flex items-center gap-2">
            <span className="text-sm">{mapMinX}</span>
            <Slider
              value={x}
              max={mapMaxX}
              min={mapMinX}
              onChange={e => setX(e.value as number)}
              onSlideEnd={onChangeX}
              className="w-[150px]"
            />
            <span className="text-sm">{mapMaxX}</span>
          </div>
        </div>
        <div className="slider">
          <span>Y: {y}</span>
          <div className="flex items-center gap-2">
            <span className="text-sm">{mapMinY}</span>
            <Slider
              value={y}
              max={mapMaxY}
              min={mapMinY}
              onChange={e => setY(e.value as number)}
              onSlideEnd={onChangeY}
              className="w-[150px]"
            />
            <span className="text-sm">{mapMaxY}</span>
          </div>
        </div>
        <AutoComplete
          value={search}
          suggestions={users}
          onChange={(e) => setSearch(e.value)}
          delay={1000}
          completeMethod={searchUsers}
          dropdown
          dropdownMode="current"
          onSelect={event => setParams({ ...params, nick_name: event.value })}
        />
        <Button label={t('common.reset')} onClick={clear} />
      </div>
      <DataTable
        value={buildings}
        stripedRows
        paginator
        rows={10}
        rowsPerPageOptions={[10, 25]}
      >
        <Column field="title" header={t('buildings.one')} sortable body={buildingTypeTemplate} />
        <Column field="nickName" header={t('common.owner')} sortable />
        <Column field="square" header={t('common.square')} sortable />
        <Column field="x" header="X" />
        <Column field="y" header="Y" />
      </DataTable>
    </div>
  )
}

export default SearchBuilding
