// frontend/react/src/components/MoveResource.tsx
import React, { useState } from 'react'
import { moveResource } from '../hooks/moveResource'
import { formatDuration } from '../include/formatDuration'
import { IResources } from '../models'
import { Error } from './Error'
import { Modal } from './Modal'
import { Success } from './Success'

interface MoveProps {
  onClose: () => void;
  resource: IResources;
}

export const MoveResource = ({ onClose, resource }: MoveProps) => {
  const [amount, setAmount] = useState(0)
  const [toX, setToX] = useState(Number(0))
  const [toY, setToY] = useState(Number(0))
  const [error, setError] = useState('')
  const [message, setMessage] = useState('')
  const distance = ((resource.x-toX)**2 + (resource.y-toY)**2)**(0.5)
  const price = (resource.weight + resource.volume) * distance * amount / 1000

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault()
    setError('')
    setMessage('')
    await moveResource(resource.resourceTypeId, amount, resource.x, resource.y, toX, toY, setMessage, setError)
  }

  return (
    <Modal title="Move Resources" onClose={onClose}>
      <Error error={error}/>
      <Success message={message}/>
      <div className="text-xl">
        <span className="font-bold">{resource.name}</span> move from <span
          className="font-bold">{resource.x}:{resource.y}</span> to
      </div>
      <form className="" onSubmit={handleSubmit}>
        <div className="flex space-x-3">
          <div className="flex flex-col">
            <label htmlFor="x" className="block text-xl font-bold">X:</label>
            <input type="number" id="x" name="x" value={toX}
              className="border-indigo-800 border-2 rounded-md px-2 w-16"
              onChange={(e) =>
                setToX(Number(e.target.value))}
            />
          </div>
          <div className="flex flex-col">
            <label htmlFor="y" className="block text-xl font-bold">Y:</label>
            <input type="number" id="y" name="y" value={toY}
              className="border-indigo-800 border-2 rounded-md px-2 w-16"
              onChange={(e) =>
                setToY(Number(e.target.value))}
            />
          </div>
        </div>
        <div className="mt-4">
          <label htmlFor="Amount" className="block text-xl font-bold">Amount:</label>
          <input name="amount" id="amount" type="number" className="border-2 w-24"
            onChange={event => {
              setAmount(parseInt(event.target.value))
            }}></input>
        </div>
        <div className="mt-4 font-bold">Estimate price: {price} </div>
        <div className="font-bold">Estimate time: {formatDuration(distance*600)} </div>
        <button type="submit"
          className="mt-4 bg-indigo-500 text-white w-1/2 py-1 px-4 rounded-md hover:bg-indigo-600"> Move
        </button>
      </form>
    </Modal>
  )
}

// frontend/vue/src/components/Resources/MoveResource.vue
<template>
  <div class="flex flex-col gap-4">
    <MessageBlock
        v-if="message"
        :message="message"
    />
    <p class="text-xl">
      Move
      <span class="font-bold">
        {{ resource.name }}
      </span>
      from
      <span class="font-bold">
        {{ resource.x }}:{{ resource.y }}
      </span>
      to
    </p>
    <div class="flex gap-4">
      <div class="flex flex-col">
        <label class="font-bold text-xl">X:</label>
        <InputNumber
          v-model="x"
          show-buttons
          :min="-2"
          :max="2"
          input-class="w-12"
        />
      </div>
      <div class="flex flex-col">
        <label class="font-bold text-xl">Y:</label>
        <InputNumber
          v-model="y"
          show-buttons
          :min="-2"
          :max="2"
          input-class="w-12"
        />
      </div>
    </div>
    <div class="flex flex-col">
      <label class="font-bold text-xl">Amount:</label>
      <InputNumber
        v-model="amount"
        show-buttons
        :step="10"
        class="w-1/2"
      />
    </div>
    <p class="font-bold">
      Estimate price: {{ price }}
    </p>
    <p class="font-bold">
      Estimate time: {{ distance }}
    </p>
    <Button
      label="Move"
      @click="move"
      class="w-1/2 self-center mt-4"
    />
  </div>
</template>

<script setup lang="ts">
import Button from 'primevue/button'
import InputNumber from 'primevue/inputnumber'
import { computed, ref } from 'vue'
import MessageBlock from '@/components/Common/MessageBlock.vue'
import { useResources } from '@/composables/useResources'
import type { Message } from '@/types'
import type { Resource } from '@/types/Resources/index.interface'

interface Props {
  resource: Resource;
}
const props = defineProps<Props>()
const emits = defineEmits<{(e: 'close'): void}>()

const x = ref<number>(0)
const y = ref<number>(0)
const amount = ref<number>(0)
const message = ref<Message | null>(null)
const { moveResource } = useResources()

const distance = computed(() => {
  return ((props.resource.x-x.value)**2 + (props.resource.y-y.value)**2)**(0.5)
})
const price = computed(() => {
  return (props.resource.weight + props.resource.volume) * distance.value * amount.value / 1000
})

const move = () => {
  const payload = {
    toX: x.value,
    toY: y.value,
    amount: amount.value,
    resourceTypeId: props.resource.resourceTypeId,
    fromX: props.resource.x,
    fromY: props.resource.y
  }
  const { onFetchResponse, dataMessage } = moveResource(payload)
  onFetchResponse(() => {
    message.value = dataMessage.value

    setTimeout(() => {
      if (dataMessage.value?.status === 'success') {
        emits('close')
      }
    }, 2000)
  })
}
</script>

<style scoped>

</style>
