// frontend/react/src/pages/Orders.tsx
import React from 'react'
import { closeOrder } from '../hooks/closeOrder'
import { useGetData } from '../hooks/getData'
import { IOrder } from '../models'

const OrdersPage = () => {
  const myOrders = useGetData<IOrder>('/market/order/my')

  return (
    <div className="p-4 mb-4 md:mb-0 shadow-xl">
      <h2 className="font-bold text-2xl">Orders</h2>
      <div className="grid grid-cols-5 gap-2 font-bold">
        <h3 className="col-span-1">Cell</h3>
        <h3 className="col-span-1">Resource</h3>
        <h3 className="col-span-1">Amount</h3>
        <h3 className="col-span-1">Price</h3>
        <h3 className="col-span-1">Type (Close)</h3>
      </div>
      {myOrders?.map((order, Index) => {
        return (
          <div className="grid grid-cols-5 " key={Index}>
            <p className="col-span-1">{order.x}:{order.y}</p>
            <p className="col-span-1">{order.resourceName}</p>
            <p className="col-span-1">{order.amount}</p>
            <p className="col-span-1">{order.priceForUnit}$</p>
            <p className="col-span-1 text-red-600 font-bold">
              <span onClick={() => closeOrder(order.id, () => {}, () => {})}>
                {order.sell ? 'sell' : 'buy'}</span></p>
          </div>
        )})}
      <p className="text-white"></p>
    </div>
  )
}

export default OrdersPage

// frontend/vue/src/components/Orders/Orders.vue
<template>
  <h2 class="mb-5 text-center">
    {{ t(`storages.title`) }}
  </h2>
  <DataTable
    v-if="!isFetching"
    :value="orders"
    size="small"
    striped-rows
  >
    <Column
      :header="t(`map.cell`)"
      class="w-1/5"
    >
      <template #body="{data}: {data: Order}">
        {{ data.x }}x{{ data.y }}
      </template>
    </Column>
    <Column
      field="resourceName"
      :header="t(`orders.columns.resource`)"
      class="w-1/5"
    />
    <Column
      field="amount"
      :header="t(`orders.columns.amount`)"
      class="w-1/5"
    />
    <Column
      field="priceForUnit"
      :header="t(`orders.columns.price`)"
      class="w-1/5"
    >
      <template #body="{data}: {data: Order}">
        {{ moneyFormat(data.priceForUnit) }}
      </template>
    </Column>
    <Column
      :header="t(`orders.columns.type`)"
      class="w-1/5"
    >
      <template #body="{data}: {data: Order}">
        <p class="font-bold text-red-500 hover:text-red-700 block" @click="closeOrder(data.id)">
          {{ data.sell ? 'sell' : 'buy' }}
        </p>
      </template>
    </Column>
  </DataTable>
  <Loading v-else />
</template>
<script setup lang="ts">
import Button from 'primevue/button'
import Column from 'primevue/column'
import DataTable from 'primevue/datatable'
import { useI18n } from 'vue-i18n'
import { moneyFormat } from '../../utils/moneyFormat'
import Loading from '@/components/Common/Loading.vue'
import { useGetData } from '@/composables/useGetData'
import { useOrders } from '@/composables/useOrders'
import { Order, Storage } from '@/types'

const { data: orders, isFetching } = useGetData<Order[]>('/market/order/my')
const { closeOrder } = useOrders()

const { t } = useI18n()
</script>
