// frontend/vue/src/components/Characteristics/Characteristics.vue
<template>
  <Card>
    <template #content>
      <h2 class="font-bold mb-2 text-2xl">
        {{ t('user.characteristics') }}
      </h2>
      <div v-if="!isFetching" class="grid gap-1">
        <p v-for="char in Object.keys(characteristics)" :key="char">
          {{ t(`user.${char}`) }}: {{ characteristics[char as keyof Characteristics] }}
        </p>
      </div>
      <Loading v-else />
    </template>
  </Card>
</template>

<script setup lang="ts">
import Card from 'primevue/card'
import { computed, type Ref } from 'vue'
import { useI18n } from 'vue-i18n'
import Loading from '@/components/Common/Loading.vue'
import { useGetData } from '@/composables/useGetData'
import type { Characteristics, User } from '@/types'

const { t } = useI18n()
const { data, isFetching } = useGetData<User>('/user/data')

const characteristics: Ref<Characteristics> = computed(() => {
  return {
    memory: data.value?.characteristics.memory,
    intelligence: data.value?.characteristics.intelligence,
    attention: data.value?.characteristics.attention,
    wits: data.value?.characteristics.wits,
    multitasking: data.value?.characteristics.multitasking,
    management: data.value?.characteristics.management,
    planning: data.value?.characteristics.planning
  }
})

</script>

<style scoped>

</style>

// frontend/react/src/components/Characteristics.tsx
import React from 'react'
import { useTranslation } from 'react-i18next'
import { useGetEntity } from '../hooks/getData'
import { Characteristics, IUser } from '../models'

const CharacteristicsPage = () => {
  const userData = useGetEntity<IUser>('/user/data')
  const { t } = useTranslation()

  const characteristics: Characteristics = {
    memory: userData?.memory,
    intelligence: userData?.intelligence,
    attention: userData?.attention,
    wits: userData?.wits,
    multitasking: userData?.multitasking,
    management: userData?.management,
    planning: userData?.planning
  }

  return (
    <div className="p-4 mb-4 md:mb-0 shadow-xl">
      <h2 className="font-bold mb-2 text-2xl">{t('user.characteristics')}</h2>
      <div className="grid gap-1">
        {Object.keys(characteristics).map(item => item && <p key={item}>{t(`user.${item}`)}: {characteristics[item as keyof Characteristics]}</p>)}
      </div>
    </div>
  )
}

export default CharacteristicsPage
