// frontend/react/src/pages/Buildings.tsx
import React from 'react'
import { useGetData } from '../hooks/getData'
import { formatDuration } from '../include/formatDuration'
import { IBuildings } from '../models'

const BuildingsPage = () => {
  const myBuildings = useGetData<IBuildings>('/building/my')

  return (
    <div className="p-4 mb-4 md:mb-0 shadow-xl">
      <h2 className="font-bold text-2xl">Buildings
        <a className="text-blue-500 hover:text-blue-700"
          href="/construct_building/0/0"> Construct</a>
      </h2>
      <div className="text-black">
        <div className="grid grid-cols-4 gap-2 font-bold">
          <h3 className="col-span-1">Building</h3>
          <h3 className="col-span-1">Cell</h3>
          <h3 className="col-span-1">Status</h3>
          <h3 className="col-span-1">Finish</h3>
        </div>
        {myBuildings?.map((building, Index) => {
          let diffS: number | null
          building.workEnd = new Date(building.workEnd)
          const now = new Date()
          diffS = Math.floor((building.workEnd.getTime() - now.getTime()) / 1000)
          if (diffS < 0) diffS = null
          return (
            <div className="grid grid-cols-4 " key={Index}>
              <p className="col-span-1 font-bold text-blue-500 hover:text-blue-700">
                <a href={`/building/${building.id}`}>{building.title} {building.level}x{building.square}</a></p>
              <p className="col-span-1">{building.x}x{building.y}</p>
              <p className="col-span-1">{building.status}</p>
              <p className="col-span-1 ml-2">{diffS && formatDuration(diffS)}</p>
            </div>
          )
        })
        }
      </div>
    </div>
  )
}

export default BuildingsPage

// frontend/vue/src/pages/buildings.vue
<template>
  <div v-if="!isFetching">
    <h2 class="font-bold text-2xl">
      Buildings
      <router-link
        class="text-blue-500 hover:text-blue-700"
        :to="{name: 'ConstructBuilding', query: {x: 0, y: 0}}"
      >
        Construct
      </router-link>
    </h2>
    <div class="text-black">
      <div class="grid grid-cols-4 gap-2 font-bold">
        <h3 class="col-span-1">
          Building
        </h3>
        <h3 class="col-span-1">
          Cell
        </h3>
        <h3 class="col-span-1">
          Status
        </h3>
        <h3 class="col-span-1">
          Finish
        </h3>
      </div>

      <div
        v-for="building in buildings"
        class="grid grid-cols-4 "
        :key="building.id"
      >
        <p class="col-span-1 font-bold text-blue-500 hover:text-blue-700">
          <router-link :to="{name: `Building${building.buildingGroup}Id`, params: {id: building.id}}">
            {{ building.title }} {{ building.level }}x{{ building.square }}
          </router-link>
        </p>

        <p class="col-span-1">
          {{ building.x }}x{{ building.y }}
        </p>
        <p class="col-span-1">
          {{ building.status }}
        </p>
        <p class="col-span-1 ml-2" v-if="getTimeDiff(building.workEnd) > 0">
          {{ formatDuration(getTimeDiff(building.workEnd)) }}
        </p>
      </div>
    </div>
  </div>
  <Loading v-else />
</template>

<script setup lang="ts">
import Loading from '@/components/Common/Loading.vue'
import { useGetData } from '@/composables/useGetData'
import type { Building } from '@/types/Buildings/index.interface'
import { formatDuration } from '@/utils/formatDuration'
import { getTimeDiff } from '@/utils/getTimeDiff'

const { data: buildings, isFetching } = useGetData<Building[]>('/building/my')
</script>

<style scoped>

</style>
