// frontend/react/src/pages/Resources.tsx
import React, { useState } from 'react'
import { MoveResource } from '../components/MoveResource'
import { SellResource } from '../components/SellResource'
import { useGetData } from '../hooks/getData'
import { IResources } from '../models'

const ResourcesPage = () => {
  const myResources = useGetData<IResources>('/resource/my')
  const [moveModal, setMoveModal] = useState(false)
  const [sellModal, setSellModal] = useState(false)
  const [resource, setResource] = useState<IResources>()
  const resourceClickHandler = async (resource: IResources) => {
    setMoveModal(true)
    setResource(resource)
  }
  const sellClickHandler = async (resource: IResources) => {
    setSellModal(true)
    setResource(resource)
  }

  return (
    <>
      {moveModal && resource && <MoveResource onClose={() => {
        setMoveModal(false)
      }} resource={resource}/>}
      {sellModal && resource && <SellResource onClose={() => {
        setSellModal(false)
      }} resource={resource}/>}
      <div className="p-4 mb-4 md:mb-0 shadow-xl">
        <h2 className="font-bold text-2xl">Resources</h2>
        <div className="grid grid-cols-4 gap-2 font-bold">
          <h3 className="col-span-1">Resource</h3>
          <h3 className="col-span-1">Amount</h3>
          <h3 className="col-span-1">Cell</h3>
          <h3 className="col-span-1">Sell</h3>
        </div>
        {myResources?.map((resource, Index) => {
          return (
            resource.amount >= 1 &&
            <div className="grid grid-cols-4 " key={Index}>
              <p className="col-span-1 font-bold text-blue-500 hover:text-blue-700" onClick={() => resourceClickHandler(resource)}>{resource.name}</p>
              <p className="col-span-1">{resource.amount.toFixed(1)}</p>
              <p className="col-span-1">{resource.x}x{resource.y}</p>
              <p className="col-span-1 font-bold text-blue-500 hover:text-blue-700" onClick={() => sellClickHandler(resource)}>Sell</p>
            </div>
          )})}
        <p className="text-white"></p>
      </div>
    </>
  )
}

export default ResourcesPage

// frontend/vue/src/pages/resources.vue
<template>
  <div v-if="!isFetching">
    <h2 class="font-bold text-2xl">
      Resources
    </h2>
    <div class="grid grid-cols-4 font-bold">
      <h3 class="col-span-1">
        Resource
      </h3>
      <h3 class="col-span-1">
        Amount
      </h3>
      <h3 class="col-span-1">
        Cell
      </h3>
      <h3 class="col-span-1">
        Sell
      </h3>
    </div>
    <div
      v-for="resource in resources"
      class="grid grid-cols-4"
      :key="resource.id"
    >
      <p class="col-span-1" @click="openMoveResource(resource)">
        {{ resource.name }}
      </p>
      <p class="col-span-1">
        {{ resource.amount }}
      </p>
      <p class="col-span-1">
        {{ resource.x }}x{{ resource.y }}
      </p>
      <p class="col-span-1" @click="openSellResource(resource)">
        sell
      </p>
    </div>
  </div>
  <Loading v-else />

  <Dialog
    v-model:visible="moveResourcesModal"
    modal
    header="Move resource"
    :style="{ width: '25rem' }"
    :breakpoints="{ '1199px': '75vw', '575px': '90vw' }"
    :dismissable-mask="true"
  >
    <MoveResource
      :resource="currentResource"
      @close="moveResourcesModal = false"
    />
  </Dialog>
  <Dialog
    v-model:visible="sellResourcesModal"
    modal
    header="Sell resource"
    :style="{ width: '25rem' }"
    :breakpoints="{ '1199px': '75vw', '575px': '90vw' }"
    :dismissable-mask="true"
  >
    <CreateOrderModal
      :resource="currentResource"
      @close="sellResourcesModal = false"
    />
  </Dialog>
</template>

<script setup lang="ts">

import Dialog from 'primevue/dialog'
import { ref } from 'vue'
import Loading from '@/components/Common/Loading.vue'
import CreateOrderModal from '@/components/Market/CreateOrderModal.vue'
import MoveResource from '@/components/Resources/MoveResource.vue'
import { useGetData } from '@/composables/useGetData'
import type { Resource } from '@/types/Resources/index.interface'

const { data: resources, isFetching } = useGetData<Resource[]>('/resource/my')

const moveResourcesModal = ref<boolean>(false)
const sellResourcesModal = ref<boolean>(false)
const currentResource = ref<Resource>({} as Resource)

const openMoveResource = (resource: Resource) => {
  currentResource.value = resource
  moveResourcesModal.value = true
}

const openSellResource = (resource: Resource) => {
  currentResource.value = resource
  sellResourcesModal.value = true
}

</script>

<style scoped>

</style>
