// frontend/vue/src/components/Resources/ResourceCard.vue
<template>
  <Card
    @click="emits('select', blueprint.id)"
    :class="{'bg-blue-200': selectedBlueprint === blueprint.id}"
    class="w-full relative"
  >
    <template #title>
      <span class="text-xl">{{ blueprint.name }}</span>
    </template>
    <template #content>
      <div class="flex flex-col gap-2">
        <p class="font-bold">
          Produce:
        </p>
        <div>
          <p
            v-for="resource in blueprint.producedResources"
            :key="resource.resourceId"
            class="ml-4"
          >
            {{ findResourceName(resourceTypes, resource.resourceId) }} {{ resource.amount }}
          </p>
        </div>
        <p class="font-bold">
          Use:
        </p>
        <div>
          <p
            v-for="resource in blueprint.usedResources"
            :key="resource.resourceId"
            class="ml-4"
          >
            {{ findResourceName(resourceTypes, resource.resourceId) }} {{ resource.amount }}
          </p>
        </div>
        <p><span class="font-bold">1 cycle time</span>: {{ blueprint.productionTime / 1000000000 }}s</p>
        <img
          class="max-h-[64px] absolute top-4 right-4"
          :src="getMinioURL(`/resource/${buildingIcon}`)"
          :alt="buildingIcon"
        />
      </div>
    </template>
  </Card>
</template>

<script setup lang="ts">
import Card from 'primevue/card'
import type { Blueprint } from '@/types/Buildings/index.interface'
import type { ResourceType } from '@/types/Resources/index.interface'
import { findResourceName } from '@/utils/findResourceName'
import { getMinioURL } from '@/utils/getMinioURL'

interface Props {
  blueprint: Blueprint;
  resourceTypes: ResourceType[];
  selectedBlueprint: number | undefined;
}

const props = defineProps<Props>()

const emits = defineEmits<{(e: 'select', value: number)}>()

const buildingIcon = findResourceName(props.resourceTypes, props.blueprint.producedResources[0].resourceId )
</script>

<style scoped>

</style>

// frontend/react/src/components/Buildings/ResourceCard/index.tsx
import React from 'react'
import config from '../../../config'
import { findResourceName } from '../../../include/findResourceName'
import { IBlueprint, IResourceAmount, IResourceTypes } from '../../../models'
import './index.scss'

const resourcesList = (resources: IResourceAmount[], resourceTypes: IResourceTypes[] | undefined) => {
  return (
    resources.map(resource =>
      <div key={resource.resourceId} className="text-l font-normal ml-4">
        {findResourceName(resourceTypes, resource.resourceId)} {resource.amount}
      </div>)
  )
}

const ResourceCard = ({ blueprint, resourceTypes, selectedBlueprint, pickBlueprint }: Props) => {
  const buildingIcon = findResourceName(resourceTypes, blueprint.producedResources[0].resourceId)

  return (
    <div
      className={`card ${selectedBlueprint === blueprint.id ? 'bg-blue-200' : 'bg-white'}`}
      onClick={() => pickBlueprint(blueprint.id)}
    >
      <p className="text-xl">{blueprint.name}</p>
      <p>Produce:</p>
      {
        resourcesList(blueprint.producedResources, resourceTypes)
      }
      <p>Use:</p>
      {
        resourcesList(blueprint.usedResources, resourceTypes)
      }
      <p>1 cycle time: {blueprint.productionTime / 1000000000}s</p>
      <img
        className="max-h-[64px] absolute top-4 right-4"
        src={`${config.minioUrl}/resource/${buildingIcon}.png`}
        alt={buildingIcon}
      />
    </div>
  )
}

type Props = {
  blueprint: IBlueprint;
  resourceTypes: IResourceTypes[] | undefined;
  selectedBlueprint: number | null;
  pickBlueprint: (id: number) => void;
}

export default ResourceCard
